package com.linuxtips.aulaaovivotesterestassured.model;


import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "curso")
public class Curso {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String cursoId;

    @DynamoDBAttribute
    private String nome;


    @DynamoDBAttribute
    private Double valor;

    @DynamoDBAttribute
    private String pessoaInstrutora;

    public String getCursoId() {
        return cursoId;
    }

    public void setCursoId(String cursoId) {
        this.cursoId = cursoId;
    }

    public String getNome() {
        return nome;
    }

    public void setNome(String nome) {
        this.nome = nome;
    }

    public Double getValor() {
        return valor;
    }

    public void setValor(Double valor) {
        this.valor = valor;
    }

    public String getPessoaInstrutora() {
        return pessoaInstrutora;
    }

    public void setPessoaInstrutora(String pessoaInstrutora) {
        this.pessoaInstrutora = pessoaInstrutora;
    }

    public Curso(String cursoId, String nome, Double valor, String pessoaInstrutora) {
        this.cursoId = cursoId;
        this.nome = nome;
        this.valor = valor;
        this.pessoaInstrutora = pessoaInstrutora;
    }

    public Curso() {
    }
}
